### ISSUE TITLE
Font Error

### ISSUE THREAD

**Issue by andrewdavis-dev** [zeeshanu/dingo-project-managment#3]
Great job on this app, I have thought about making something similar in Laravel before but haven't had the time. I like the similarities with Trello.

After install, I noticed the font wasn't loading correctly, I had to change the class in app.css from:
`body {
    font-family: "Open Sans";
}`
to:
`body {
    font-family: "Open Sans", sans-serif;
}`

Thanks!

**Comment by ziishaned** [comment]
Thanks for pointing this out. :+1:
